### ISSUE TITLE
Failed to build biostar145820 (Build file '/jvarkit/build.gradle' line: 676)

### ISSUE THREAD

**Issue by gilhornung** [lindenb/jvarkit#184]
### Verify
* if you cannot compile/install , read https://github.com/lindenb/jvarkit/wiki/Compilation before submitting a new issue
* the version of java
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode)
```

### Subject of the issue
Installation of biostar145820 failed

### Your environment
I'm trying to install within a docker. Here is the dockerfile:
```
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get update --fix-missing

RUN apt-get install -y build-essential
RUN apt-get install -y wget
RUN apt-get install -y libssl-dev
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libbz2-dev
RUN apt-get install -y liblzma-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y git

# Install cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1.tar.gz

RUN tar -xvf cmake-3.21.1.tar.gz
RUN rm cmake-3.21.1.tar.gz

RUN cd cmake-3.21.1 && \
    ./bootstrap && \
    make && \
    make install

# Install htslib
RUN wget https://github.com/samtools/htslib/releases/download/1.13/htslib-1.13.tar.bz2
RUN bzip2 -d htslib-1.13.tar.bz2 && \
    tar -xvf htslib-1.13.tar && \
	cd htslib-1.13/ && \
	make

# Install OpenJDK-11
RUN apt-get update && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean;

ENV JAVA_HOME="/usr/lib/jvm/java-1.11.0-openjdk-amd64/"
ENV PATH="/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin:${PATH}"

RUN apt-get install -y default-jdk

RUN git clone "https://github.com/lindenb/jvarkit.git" && \
    cd jvarkit
```

### Steps to reproduce
From within the docker I am trying:
`./gradlew --info biostar145820`

### Expected behaviour
Should install

### Actual behaviour
Tell us what happens instead
Here is the output:
```
Initialized native services in: /root/.gradle/native
The client will now receive all logging from the daemon (pid: 61). The daemon log file: /root/.gradle/daemon/6.7/daemon-61.out.log
Starting 3rd build in daemon [uptime: 26 mins 58.895 secs, performance: 98%, non-heap usage: 24% of 268.4 MB]
Using 4 worker leases.
Watching the file system is disabled
Starting Build
Settings evaluated using settings file '/jvarkit/settings.gradle'.
Projects loaded. Root project using build file '/jvarkit/build.gradle'.
Included projects: [root project 'jvarkit']

> Configure project :
Evaluating root project 'jvarkit' using build file '/jvarkit/build.gradle'.
All projects evaluated.
Selected primary task 'biostar145820' from project :
Tasks to be executed: [biostar145820 com.github.lindenb.jvarkit.tools.biostar.Biostar145820]
Tasks that were excluded: []
:biostar145820 (Thread[Daemon worker Thread 2,5,main]) started.
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 8
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0xE2) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                         ^
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0x80) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                          ^
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0x93) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                           ^
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0xE2) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                                                                                                                                    ^
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0x80) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                                                                                                                                     ^
[ant:javac] /jvarkit/src/main/java/com/github/lindenb/jvarkit/tools/biostar/Biostar145820.java:77: error: unmappable character (0x93) for encoding US-ASCII
[ant:javac]     references={"MED25 connects enhancer???promoter looping and MYC2-dependent activation of jasmonate signalling. Wang et al. Nature Plants 5, 616???625 (2019)  https://doi.org/10.1038/s41477-019-0441-9 "}
[ant:javac]                                                                                                                                                      ^
[ant:javac] 6 errors
[ant:javac] 1 warning

> Task :biostar145820 FAILED
Starting process 'command 'git''. Working directory: /jvarkit Command: git rev-parse --short HEAD
Successfully started process 'command 'git''
Caching disabled for biostar145820 com.github.lindenb.jvarkit.tools.biostar.Biostar145820 because:
  Build cache is disabled
Biostar145820 com.github.lindenb.jvarkit.tools.biostar.Biostar145820 is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'which''. Working directory: /jvarkit Command: which java
Successfully started process 'command 'which''
Starting process 'command 'which''. Working directory: /jvarkit Command: which javac
Successfully started process 'command 'which''
Starting process 'command 'which''. Working directory: /jvarkit Command: which jar
Successfully started process 'command 'which''
[ant:javac] Compiling 1 source file to /jvarkit/tmp
:biostar145820 (Thread[Daemon worker Thread 2,5,main]) completed. Took 0.533 secs.

FAILURE: Build failed with an exception.

* Where:
Build file '/jvarkit/build.gradle' line: 676

* What went wrong:
Execution failed for biostar145820 com.github.lindenb.jvarkit.tools.biostar.Biostar145820.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

The build stack is:
https://scans.gradle.com/s/wu7lwpyx2pn4m

**Comment by lindenb** [comment]
@gilhornung  thank you for the bug report. The problem was caused by an unicode character in the code. I hope it's fixed now.
